// NextGenSoftware.OASIS.API.ONODE.WebUI.HTML/ClientApp/oasis-angular/oasis-web/src/app/components/side-nav/side-nav.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-side-nav',
  templateUrl: './side-nav.component.html',
  styleUrls: ['./side-nav.component.scss'],
})
export class SideNavComponent implements OnInit {
  constructor() {}
  stylesObj: any = { 'is-visible': false };
  @Input() visible: boolean = false;
  @Output() visibleChange: EventEmitter<boolean> = new EventEmitter<boolean>();
  ngOnInit(): void {}
  // toggleMenu() {
  //   this.visible = !this.visible;
  //   this.stylesObj['is-visible'] = this.visible;
  //   this.visibleChange.emit(this.visible);
  // }
}

<nav class="side-nav js-side-nav" [ngClass]="{'is-visible':visible}">
    <ul class="side__list js-side__list ">
        <!-- <li class="side__item">
          <form class="search js-search" autocomplete="off">
            <label class="sr-only" for="search">Search</label>
            <input class="reset search__input js-search__input" type="search" name="search" id="search"
              placeholder="Search...">
            <button class="reset search__btn">
              <svg class="icon" viewBox="0 0 24 24">
                <title>Search</title>
                <g stroke-linecap="square" stroke-linejoin="miter" stroke-width="2" stroke="currentColor" fill="none"
                  stroke-miterlimit="10">
                  <line x1="21" y1="21" x2="15.656" y2="15.656" />
                  <circle cx="10" cy="10" r="8" />
                </g>
              </svg>
            </button>
          </form>
        </li> -->
        <li class="side__item item--has-children js-item--has-children">
            <a href="#" (click)="menuItemClick($event)">The Oasis</a>
            <ul class="sub-menu">
                <li> <a target="_blank"
                        href="https://drive.google.com/file/d/1nnhGpXcprr6kota1Y85HDDKsBfJHN6sn/view?usp=sharing">About</a>
                </li>
                <li> <a target="_blank"
                        href="https://github.com/NextGenSoftwareUK/Our-World-OASIS-API-HoloNET-HoloUnity-And-.NET-HDK">Documentation</a>
                </li>
                <li> <a target="_blank" href="#" href="http://www.ourworldthegame.com">Our World</a>
                </li>
            </ul>
        </li>
        <li class="side__item item--has-children js-item--has-children">
            <a href="#" (click)="menuItemClick($event)">Avatar</a>
            <ul class="sub-menu">
                <li> <a onclick="showCheckAPIMessage();" href="#">View Avatar</a> </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">Edit Avatar</a> </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">Search Avatars</a> </li>
            </ul>
        </li>
        <li class="side__item item--has-children js-item--has-children">
            <a href="#" (click)="menuItemClick($event)">Karma</a>
            <ul class="sub-menu">
                <li> <a onclick="showComingSoonMessage();" href="#"> View Curent Karma Weightings</a>
                </li>
                <li> <a onclick="showComingSoonMessage();" href="#"> Vote For Karma Weightings</a></li>
                <li> <a onclick="showCheckAPIMessage();" href="#"> View Avatar Karma</a></li>
                <li> <a onclick="showCheckAPIMessage();" href="#"> View/Search Karma Akashic Records</a>
                </li>
            </ul>
        </li>
        <li class="side__item item--has-children js-item--has-children">
            <a href="#" (click)="menuItemClick($event)">Data</a>
            <ul class="sub-menu">
                <li> <a onclick="showCheckAPIMessage();" href="#">Load Data</a> </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">Send Data</a> </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">Manage Data</a> </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">Cross-Chain Management</a>
                </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">Off-Chain Management</a></li>
                <li> <a onclick="showComingSoonMessage();" href="#">Search Data</a> </li>
            </ul>
        </li>
        <li class="side__item item--has-children js-item--has-children">
            <a href="#" (click)="menuItemClick($event)">SEEDS</a>
            <ul class="sub-menu">
                <li> <a onclick="showCheckAPIMessage();" href="#">Pay With SEEDS</a> </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">Donate SEEDS</a> </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">Reward SEEDS</a> </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">Invite To Join Seeds</a></li>
                <li> <a onclick="showCheckAPIMessage();" href="#">Accept Invite To Join Seeds</a></li>
                <li> <a onclick="showCheckAPIMessage();" href="#">View SEEDS</a> </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">View Organisations</a></li>
                <li> <a onclick="showCheckAPIMessage();" href="#">Manage SEEDS</a> </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">Search Seeds</a> </li>
            </ul>
        </li>
        <li class="side__item item--has-children js-item--has-children">
            <a href="#" (click)="menuItemClick($event)">Provider</a>
            <ul class="sub-menu">
                <li> <a onclick="showCheckAPIMessage();" href="#">View Providers</a> </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">Manage Providers</a> </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">Manage Auto-Replication</a>
                </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">Manage Auto-Fail-Over</a>
                </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">Manage Load Balancing</a>
                </li>
                <li> <a onclick="showComingSoonMessage();" href="#">View Provider Stats</a>
                </li>
                <li> <a onclick="showComingSoonMessage();" href="#">Compare Provider Speeds</a>
                </li>
                <li> <a onclick="showComingSoonMessage();" href="#">Search Providers</a></li>
                <li> <a onclick="showComingSoonMessage();" href="#">Holochain</a> </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">SEEDS</a> </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">EOSIO</a> </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">Ethereum</a> </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">IPFS</a> </li>
                <li> <a onclick="showComingSoonMessage();" href="#">ThreeFold</a> </li>
                <li> <a onclick="showComingSoonMessage();" href="#">SOLID</a> </li>
                <li> <a onclick="showComingSoonMessage();" href="#">Activity Pub</a> </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">Mongo DB</a> </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">SQLLite</a> </li>
                <li> <a onclick="showCheckAPIMessage();" href="#">Neo4j</a> </li>
            </ul>
        </li>
        <li class="side__item item--has-children js-item--has-children">
            <a href="#" (click)="menuItemClick($event)">NFT</a>
            <ul class="sub-menu">
                <li> <a onclick="showComingSoonMessage();" href="#">View OASIS NFTs</a></li>
                <li> <a onclick="showComingSoonMessage();" href="#">Manage OASIS NFTs</a></li>
                <li> <a onclick="showComingSoonMessage();" href="#">Search OASIS NFTs</a></li>
                <li> <a onclick="showComingSoonMessage();" href="#">Purchase OASIS NFT</a></li>
                <li> <a onclick="showComingSoonMessage();" href="#">Purchase OASIS Virtual Land NFT </a>
                </li>
            </ul>
        </li>
        <li class="side__item item--has-children js-item--has-children">
            <a href="#" (click)="menuItemClick($event)">Map</a>
            <ul class="sub-menu">
                <li> <a onclick="showOurWorldMessage();" href="#">View Global 3D Map</a></li>
                <li> <a onclick="showOurWorldMessage();" href="#">Mange Map </a> </li>
                <li> <a onclick="showComingSoonMessage();" href="#">Add Quest To Map</a></li>
                <li> <a onclick="showComingSoonMessage();" href="#">Add 2D Object To Map</a>
                </li>
                <li> <a onclick="showComingSoonMessage();" href="#">Add 3D Object To Map</a>
                </li>
                <li> <a onclick="showComingSoonMessage();" href="#">Plot Route On Map</a></li>
                <li> <a onclick="showComingSoonMessage();" href="#">View OAPP's On Map</a></li>
                <li> <a onclick="showComingSoonMessage();" href="#">View Holons On Map</a></li>
                <li> <a onclick="showComingSoonMessage();" href="#">View Quests On Map</a></li>
                <li> <a onclick="showComingSoonMessage();" href="#">Search Map</a> </li>
                <li> <a onclick="showOurWorldMessage();" href="#">Download Our World</a></li>
            </ul>
        </li>
        <li class="side__item item--has-children js-item--has-children">
            <a href="#" (click)="menuItemClick($event)">OAPP</a>
            <ul class="sub-menu">
                <li> <a onclick="showSTARMessage();" href="#">Installed OAPPs</a> </li>
                <li> <a onclick="showSTARMessage();" href="#">Manage OAPPs</a> </li>
                <li> <a onclick="showSTARMessage();" href="#">Create OAPP</a> </li>
                <li> <a onclick="showSTARMessage();" href="#">Deploy OAPP</a> </li>
                <li> <a onclick="showSTARMessage();" href="#">Edit OAPP</a> </li>
                <li> <a onclick="showSTARMessage();" href="#">Launch OAPP</a> </li>
                <li> <a onclick="showSTARMessage();" href="#">Search OAPPs</a> </li>
                <li> <a onclick="showOurWorldMessage();" href="#">Download Our World</a></li>
            </ul>
        </li>
        <li class="side__item item--has-children js-item--has-children">
            <a href="#" (click)="menuItemClick($event)">Quest</a>
            <ul class="sub-menu">
                <li> <a onclick="showComingSoonMessage();" href="#">View Quests</a></li>
                <li> <a onclick="showComingSoonMessage();" href="#">Manage Quests</a></li>
                <li> <a onclick="showComingSoonMessage();" href="#">Search Quests </a></li>
            </ul>
        </li>
        <li class="side__item item--has-children js-item--has-children">
            <a href="#" (click)="menuItemClick($event)">Mission</a>
            <ul class="sub-menu">
                <li> <a onclick="showComingSoonMessage();" href="#">View Missions</a></li>
                <li> <a onclick="showComingSoonMessage();" href="#">Manage Missions</a></li>
                <li> <a onclick="showComingSoonMessage();" href="#">Search Missions</a></li>
            </ul>
        </li>
        <li class="side__item item--has-children js-item--has-children">
            <a href="#" (click)="menuItemClick($event)">Egg</a>
            <ul class="sub-menu">
                <li> <a onclick="showComingSoonMessage();" href="#">View Eggs</a> </li>
                <li> <a onclick="showComingSoonMessage();" href="#">Manage Eggs</a></li>
                <li> <a onclick="showComingSoonMessage();" href="#">Search Eggs</a></li>
            </ul>
        </li>
        <li class="side__item item--has-children js-item--has-children">
            <a href="#" (click)="menuItemClick($event)">Game</a>
            <ul class="sub-menu">
                <li> <a onclick="showComingSoonMessage();" href="#">View StarCraft 2 Leagues</a></li>
                <li> <a onclick="showComingSoonMessage();" href="#">View StarCraft 2 Tournaments</a></li>
                <li> <a onclick="showComingSoonMessage();" href="#">View StarCraft 2 Achievements</a>
                </li>
                <li> <a onclick="showComingSoonMessage();" href="#">Search StarCraft 2 Profiles</a></li>
            </ul>
        </li>
        <li class="side__item item--has-children js-item--has-children">
            <a href="#" (click)="menuItemClick($event)">Developer</a>
            <ul class="sub-menu">
                <div class="subtitle" style="color: #888888;">OASIS API</div>
                <li> <a target="_blank" href="https://api.oasisplatform.world">LIVE</a></li>
                <li> <a target="_blank" href="https://staging.api.oasisplatform.world">STAGING</a>
                </li>
                <li> <a target="_blank" href="https://oasisplatform.world">UI LIVE</a></li>
                <li> <a target="_blank" href="https://staging.oasisplatform.world">UI STAGING</a>
                </li>
                <li> <a onclick="showSTARMessage();" href="#">STAR ODK</a> </li>
                <li>
                    <i class="material-icons">description</i>
                    <a target="_blank" href="postman/OASIS_API.postman_collection.json">Postman <span
                            class="jsonIcon">JSON</span></a>
                </li>
                <li>
                    <i class="material-icons">description</i>
                    <a target="_blank" href="postman/OASIS_API_DEV.postman_environment.json">DEV ENVIROMENT
                        Postman <span class="jsonIcon">JSON</span></a>
                </li>
                <li>
                    <i class="material-icons">description</i>
                    <a target="_blank" href="postman/OASIS_API_STAGING.postman_environment.json">STAGING
                        ENVIROMENT Postman <span class="jsonIcon">JSON</span></a>
                </li>
                <li>
                    <i class="material-icons">description</i>
                    <a target="_blank" href="postman/OASIS_API_LIVE.postman_environment.json">LIVE ENVIROMENT
                        Postman <span class="jsonIcon">JSON</span></a>
                </li>
                <li> <a target="_blank"
                        href="https://github.com/NextGenSoftwareUK/Our-World-OASIS-API-HoloNET-HoloUnity-And-.NET-HDK">Code/Documentation</a>
                </li>
                <li> <a target="_blank" href="https://www.thejusticeleagueaccademy.icu/">The Justice League Academy</a>
                </li>
            </ul>
        </li>
        <li class="side__item js-nav__login "><a class="js-modal-trigger" href="#" (click)="menuItemClick($event)"
                data-signin="login">Log in</a>
        </li>
        <li class="side__item js-nav__login "><a class="js-modal-trigger" href="#0" data-signin="signup">Sign up</a>
        </li>
    </ul>
</nav>

// NextGenSoftware.OASIS.API.ONODE.WebUI.HTML/react-app/src/Components/SideNav.js
import React from 'react';

import SideMenu from './SideMenu';
import '../CSS/SideNav.css';

const data = [
    {
        title: "the oasis",
        subNav: ["about", "documentation", "our world"]
    }, 
    {
        title: "avatar",
        subNav: ["view avatar", "edit avatar", "search avatars"]
    }, 
    {
        title: "karma",
        subNav: [
            "View Curent Karma Weightings",
            "Vote For Karma Weightings",
            "View Avatar Karma",
            "View/Search Karma Akashic Records"
        ]
    }, 
    {
        title: "data",
        subNav: [
            "Load Data",
            "Send Data",
            "Manage Data",
            "Cross-Chain Management",
            "Off-Chain Management",
            "Search Data"

        ]
    }, 
    {
        title: "seeds",
        subNav: [
            "Pay With SEEDS",
            "Donate SEEDS",
            "Reward SEEDS",
            "Invite To Join SEEDS",
            "Accept Invit to join seeds",
            "View SEEDS",
            "View Organisations",
            "Manage SEEDS",
            "Search Seeds"
        ]
    }, 
    {
        title: "provider",
        subNav: [
            "View Providers",
            "Manage Providers",
            "Manage Auto-Replication",
            "Manage Auto-Fail-Over",
            "Manage Load Balancing",
            "View Provider Stats",
            "Compare Provider Speeds",
            "Search Providers",
            "Holochain",
            "SEEDS",
            "EOSIO",
            "Ethereum",
            "IPFS",
            "ThreeFold",
            "SOLID",
            "Activity Pub",
            "Mongo DB",
            "SQLLite",
            "Neo4j"
        ]
    }, 
    {
        title: "nft",
        subNav: []
    }, 
    {
        title: "map",
        subNav: []
    }, 
    {
        title: "oapp",
        subNav: []
    }, 
    {
        title: "quest",
        subNav: []
    }, 
    {
        title: "mission",
        subNav: []
    }, 
    {
        title: "egg",
        subNav: []
    }, 
    {
        title: "game",
        subNav: [
            "View StarCraft 2 Leagues",
            "View StarCraft 2 Tournaments",
            "View StarCraft 2 Achievements"]
    }, 
    {
        title: "developer",
        subNav: []
    }
]

export class SideNav extends React.Component {
    constructor(props) {
        super(props)

        this.state = {
            showSubNav: false
        }
    }

    render() {
        return (
            <div className={`side-nav${this.props.show ? " side-nav-show" : ""}`}>
                <ul className="side-nav-list">
                    {data.map((menu, index) => <SideMenu menu={menu} key={index} />)}
                    <li className="side-nav-logins"><div className="link-inverse" onClick={this.props.showLogin}>Log in</div> </li>
                    <li className="side-nav-logins"><div className="link-inverse" onClick={this.props.showSignup}>Sign up</div></li>
                </ul>
            </div>
        )
    }
}

export default SideNav;
